### ISSUE TITLE
Server crash in error handling

### ISSUE THREAD

**Issue by radekmie** [monti-apm/monti-apm-agent#107]
Out of nowhere (no updates, no deploys, etc.) we got a few errors like this:

```
message: Cannot read property '_skipKadira' of undefined
stack:
    TypeError: Cannot read property '_skipKadira' of undefined
    at process.<anonymous> (packages/montiapm:agent/lib/hijack/error.js:59:14)
    at process.emit (events.js:400:28)
    at process.emit (domain.js:475:12)
    at processPromiseRejections (internal/process/promises.js:245:33)
    at processTicksAndRejections (internal/process/task_queues.js:96:32)
  
```

They originate from [this code](https://github.com/monti-apm/monti-apm-agent/blob/6902150c4951547c4f88f33dc2498ea4a54200ae/lib/hijack/error.js#L13), so I guess we got `throw undefined` somewhere. With stack trace like this, there's nothing we can do. Do you think this check could be secured so it'd handle it properly?

**Comment by zodern** [comment]
Thanks for letting us know. I published v2.47.4 to fix it.
