### ISSUE TITLE
TypeError: Cannot read property 'message' of undefined

### ISSUE THREAD

**Issue by skeetmtp** [monti-apm/monti-apm-agent#126]
Hello,

Got this Unhandled Rejection: 

TypeError: Cannot read property 'message' of undefined
at TracerStore._handleErrors (packages/montiapm:agent/lib/tracer/tracer_store.js:64:51)
at TracerStore.addTrace (packages/montiapm:agent/lib/tracer/tracer_store.js:32:10)
at MethodsModel.processMethod (packages/montiapm:agent/lib/models/methods.js:83:20)
at Session.sessionProto.send (packages/montiapm:agent/lib/hijack/wrap_session.js:158:31)
at Session.kadira_Session_send [as send] (packages/montiapm:agent/lib/hijack/set_labels.js:9:25)
at packages/ddp-server/livedata_server.js:940:16

with
monti-apm-agent v2.49.3
cult-of-coders/redis-oplog latest 

Error not occurred often, but make us a bit uncomfortable enabling monti apm by default

**Comment by zodern** [comment]
Thanks for reporting this @skeetmtp. I'm not finding a way that the agent could store an undefined error in the trace. Do you use any trace filters (`Kadira.tracer.addFilter`/`Monti.tracer.addFilter`), or manually add events to the trace (`Kadira.tracer.event`/`Monti.tracer.event`)?

**Comment by skeetmtp** [comment]
Hello,

Nop, I cannot find any occurence of "tracer.addFilter" or "tracer.event" in our codebase

**Comment by zodern** [comment]
I released version 2.49.4 to handle invalid errors in traces, though I'm still not sure why it is happening.

If you set the env var `DEBUG` to `kadira:ts`, it will log a message when this happens: `trace does not have valid error` along with the full trace.

**Comment by brianlukoff** [comment]
We just saw the same thing (also using redis-oplog, but the Meteor 3 branch), using the 3.0.0-beta.4 version of montiapm:agent. Unfortunately it has only happened once and only in production so we haven't been able to catch it with debug logging.

We do use `addFilter` but only to redact sensitive parameters:
```
  Monti.tracer.addFilter((eventType, data, { type: traceType, name: traceName }) => {
    delete data.params;
    return data;
  });
  
  Monti.tracer.addFilter((eventType, data) => {
    delete data.selector;
    return data;
  });
```
