### ISSUE TITLE
RangeError: Too many properties to enumerate

### ISSUE THREAD

**Issue by gbhrdt** [monti-apm/monti-apm-agent#128]
We got this log multiple times today, the application crashed afterwards. We are using montiapm:agent 2.47.2

```
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason: 
RangeError: Too many properties to enumerate
    at Function.keys (<anonymous>)
    at lengthOf (packages/ejson/utils.js:7:41)
    at Object.matchObject (packages/ejson/ejson.js:182:26)
    at toJSONValueHelper (packages/ejson/ejson.js:244:19)
    at Object.adjustTypesToJSONValue [as _adjustTypesToJSONValue] (packages/ejson/ejson.js:258:24)
    at packages/ddp-common/utils.js:108:27
    at Array.forEach (<anonymous>)
    at DDPCommon.stringifyDDP (packages/ddp-common/utils.js:106:34)
    at Object.DDPCommon.stringifyDDP (packages/montiapm:agent/lib/hijack/wrap_ddp_stringify.js:7:21)
    at Session.send (packages/ddp-server/livedata_server.js:514:34)
    at Session.sessionProto.send (packages/montiapm:agent/lib/hijack/wrap_session.js:168:25)
    at Session.kadira_Session_send [as send] (packages/montiapm:agent/lib/hijack/set_labels.js:9:25)
    at packages/ddp-server/livedata_server.js:809:14
    at /opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
```

A few seconds before this log, there was another log related to `html-pdf` maybe it's related, not sure:

```
Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:156:25)
    at writeGeneric (internal/stream_base_commons.js:147:3)
    at Socket._writeGeneric (net.js:798:11)
    at Socket._write (net.js:810:8)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at Socket.Writable.write (internal/streams/writable.js:303:10)
    at PDF.PdfExec [as exec] (/opt/meteor/dist/bundle/programs/server/npm/node_modules/html-pdf/lib/pdf.js:141:15)
    at PDF.PdfToBuffer [as toBuffer] (/opt/meteor/dist/bundle/programs/server/npm/node_modules/html-pdf/lib/pdf.js:44:8)
    at server/routes/pdf.js:58:10
    at runWithEnvironment (packages/meteor.js:1486:24)
    at packages/meteor.js:1499:14
    at runWithEnvironment (packages/meteor.js:1486:24)
    at packages/meteor.js:1499:14
    at Layer.handle [as handle_request] (/opt/meteor/dist/bundle/programs/server/npm/node_modules/express/lib/router/layer.js:95:5)
    at next (/opt/meteor/dist/bundle/programs/server/npm/node_modules/express/lib/router/route.js:137:13)
    at next (/opt/meteor/dist/bundle/programs/server/npm/node_modules/express/lib/router/route.js:131:14)
 ```

**Comment by zodern** [comment]
I don't think this issue is related to the agent - it isn't calling EJSON.stringify, and is only wrapping the function to record the size of the string.

The error message is different, but I wonder if it is something similar to https://github.com/meteor/meteor/issues/9877.
