### ISSUE TITLE
v.3 Beta breaks the app — Cannot read properties of undefined (reading 'prototype')

### ISSUE THREAD

**Issue by kolyasya** [monti-apm/monti-apm-agent#135]
I tried to install a few v.3 beta versions in my app and for all of them I get the same issue:

```js
error on boot.js TypeError: Cannot read properties of undefined (reading 'prototype')
at hijackNextObject (packages/montiapm:agent/lib/hijack/db/hijack-next-object.js:6:42)
at hijackDBOps (packages/montiapm:agent/lib/hijack/db/index.js:46:3)
at packages/montiapm:agent/lib/hijack/instrument.js:64:5
at initAsync (packages/montiapm:meteorx/src/server.js:40:11)
```

<img width="959" alt="image" src="https://github.com/user-attachments/assets/d04b8d3d-931d-443e-a38c-a669c31c5794" />

Is that something I need to fix on my side?

**Comment by zodern** [comment]
Could you please share the Meteor versions you've tried?

**Comment by kolyasya** [comment]
@zodern it were different versions, so I don't think it is related. My latest test was on Meteor 3.1

**Comment by zodern** [comment]
Are you using `matb33:collection-hooks`? Some of beta/release candidate versions broke meteorx. The latest versions should be compatible with meteorx and montiapm:agent

**Comment by kolyasya** [comment]
@zodern yes, `matb33:collection-hooks@2.0.0-rc.3`
I'll try to update

**Comment by kolyasya** [comment]
@zodern confirm that there is no such error anymore with latest `matb33:collection-hooks@2.0.0`, thanks!
