### ISSUE TITLE
[Meteor 2.6]  : MongoInvalidArgumentError

### ISSUE THREAD

**Issue by ouya99** [monti-apm/monti-apm-agent#47]
Following the update to Meteor 2.6 (mongoDB 5) I get an error: 

`W20220213-15:04:28.762(1)? (STDERR) Monti APM: trace has not started yet
W20220213-15:04:28.763(1)? (STDERR) (node:74759) [MONGODB DRIVER] Warning: collection.update is deprecated. Use updateOne, updateMany, or bulkWrite instead.
W20220213-15:04:28.764(1)? (STDERR) (Use `node --trace-warnings ...` to show where the warning was created)
I20220213-15:04:28.764(1)? Exception from sub kadira.debug.client.init id 4aZ8eWKPskjoesxNS MongoInvalidArgumentError: Update document requires atomic operators
I20220213-15:04:28.765(1)?     at new UpdateManyOperation (/Users/alexander/.meteor/packages/npm-mongo/.4.3.1.r8ccpw.i4kri++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/operations/update.js:97:19)
I20220213-15:04:28.765(1)?     at Collection.updateMany (/Users/alexander/.meteor/packages/npm-mongo/.4.3.1.r8ccpw.i4kri++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/collection.js:178:90)
I20220213-15:04:28.765(1)?     at Collection.update (/Users/alexander/.meteor/packages/npm-mongo/.4.3.1.r8ccpw.i4kri++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/collection.js:460:21)
I20220213-15:04:28.765(1)?     at KdDataLayer.setTrace (packages/montiapm_debug.js:181:35)
I20220213-15:04:28.765(1)?     at TraceStore._onSubTrace (packages/montiapm_debug.js:371:17)
I20220213-15:04:28.765(1)?     at EventEmitter.emit (events.js:400:28)
I20220213-15:04:28.765(1)?     at EventEmitter.emit (domain.js:475:12)
I20220213-15:04:28.765(1)?     at Object.Kadira.EventBus.<computed> [as emit] (packages/montiapm:agent/lib/common/unify.js:28:26)
I20220213-15:04:28.765(1)?     at Subscription.subscriptionProto.ready (packages/montiapm:agent/lib/hijack/wrap_subscription.js:33:23)
I20220213-15:04:28.765(1)?     at Subscription.<anonymous> (packages/montiapm_debug.js:601:8)
I20220213-15:04:28.765(1)?     at packages/matb33:collection-hooks/server.js:33:71
I20220213-15:04:28.767(1)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)
I20220213-15:04:28.768(1)?     at Subscription._handler (packages/matb33:collection-hooks/server.js:33:26)
I20220213-15:04:28.768(1)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1885:12)
I20220213-15:04:28.768(1)?     at packages/ddp-server/livedata_server.js:1107:9
I20220213-15:04:28.768(1)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)
W20220213-15:04:30.819(1)? (STDERR) Monti APM: trace has not started yet
I20220213-15:04:30.820(1)? Exception from sub kadira.debug.client.init id nFgsPJ9T5P7Tt66zY MongoInvalidArgumentError: Update document requires atomic operators
I20220213-15:04:30.820(1)?     at new UpdateManyOperation (/Users/alexander/.meteor/packages/npm-mongo/.4.3.1.r8ccpw.i4kri++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/operations/update.js:97:19)
I20220213-15:04:30.820(1)?     at Collection.updateMany (/Users/alexander/.meteor/packages/npm-mongo/.4.3.1.r8ccpw.i4kri++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/collection.js:178:90)
I20220213-15:04:30.824(1)?     at Collection.update (/Users/alexander/.meteor/packages/npm-mongo/.4.3.1.r8ccpw.i4kri++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/collection.js:460:21)
I20220213-15:04:30.825(1)?     at KdDataLayer.setTrace (packages/montiapm_debug.js:181:35)
I20220213-15:04:30.825(1)?     at TraceStore._onSubTrace (packages/montiapm_debug.js:371:17)
I20220213-15:04:30.825(1)?     at EventEmitter.emit (events.js:400:28)
I20220213-15:04:30.825(1)?     at EventEmitter.emit (domain.js:475:12)
I20220213-15:04:30.825(1)?     at Object.Kadira.EventBus.<computed> [as emit] (packages/montiapm:agent/lib/common/unify.js:28:26)
I20220213-15:04:30.825(1)?     at Subscription.subscriptionProto.ready (packages/montiapm:agent/lib/hijack/wrap_subscription.js:33:23)
I20220213-15:04:30.825(1)?     at Subscription.<anonymous> (packages/montiapm_debug.js:601:8)
I20220213-15:04:30.825(1)?     at packages/matb33:collection-hooks/server.js:33:71
I20220213-15:04:30.825(1)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)
I20220213-15:04:30.825(1)?     at Subscription._handler (packages/matb33:collection-hooks/server.js:33:26)
I20220213-15:04:30.825(1)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1885:12)
I20220213-15:04:30.825(1)?     at packages/ddp-server/livedata_server.js:1107:9
I20220213-15:04:30.825(1)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)`

**Comment by zodern** [comment]
@ouya99 does it work if you remove `montiapm:debug` from your app?

**Comment by ouya99** [comment]
@zodern  yes this works
