### ISSUE TITLE
message: Method 'user-status-idle' not found [404]

### ISSUE THREAD

**Issue by ddaydd** [monti-apm/monti-apm-agent#68]
Hi, i got this error

```
message: Method 'user-status-idle' not found [404]
stack:
Error: Method 'user-status-idle' not found [404]
    at Session.method (packages/ddp-server/livedata_server.js:721:18)
    at packages/montiapm:agent/lib/hijack/wrap_session.js:65:38
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)
    at Session.sessionProto.protocol_handlers.method (packages/montiapm:agent/lib/hijack/wrap_session.js:64:44)
    at packages/ddp-server/livedata_server.js:603:43
```

**Comment by zodern** [comment]
Hi @ddaydd,

This looks like an error in your app instead of in montiapm:agent. Something in your app is calling the `user-status-idle` method, but it doesn't exist on the server.

**Comment by ddaydd** [comment]
ok, sorry, thanks
